// Generated by CoffeeScript 1.10.0
(function() {
  module.exports = {
    LoteHeader: {
      TIPO_SERVICO: {
        COBRANCA: '01',
        PAGAMENTO_DIVIDENDOS: '10',
        VENDA_ACOES: '11',
        PAGAMENTO_FORNECEDORES: '20',
        PAGAMENTO_CONTAS: '22',
        PAGAMNETO_EMPRESTIMOS: '34',
        PAGAMENTO_COMISSOES: '36',
        PAGAMENTO_LOJISTAS: '40',
        TRANSFERENCIA_TITULARIDADE: '50',
        PAGAMENTO_DESPESA_VIAJANTE: '60',
        PAGAMENTO_ADIANTAMENTO: '61',
        REEMBOLSO_DESPESA: '62',
        PAGAMENTO_AUTORIZADO: '70',
        PAGAMENTO_BENEFICIOS: '90',
        PAGAMENTO_ASSISTENCIA_MEDICA: '91',
        PAGAMENTO_PIS_PASEP: '92',
        PAGAMENTO_GPS: '95'
      },
      FORMA_LANCAMENTO: {
        CREDITO_CC: '10',
        CEDITO_ADM: '02',
        DOCTO_CREDITO: '03',
        CREDITO_POUPANCA: '05',
        PGTO_CONTAS: '11',
        DARF: '16',
        LIQUIDACAO_TITULOS_HSBC: '30',
        LIQUIDACAO_TITULOS_OUTROS: '31',
        LIBERACAO_TITULOS_HSBC: '32',
        LIQUIDACAO_PARCELAS: '33',
        GPS: '34'
      }
    },
    Detail: {
      TIPO_MOVIMENTO: {
        I: 0,
        B: 5,
        E: 9
      },
      CODIGO_MOVIMENTO: {
        INCLUSAO: '00',
        EXCLUSAO: '99',
        INCLUSAO_COM_BLOQUEIO: '55'
      }
    }
  };

}).call(this);
