// Generated by CoffeeScript 2.1.1
(function() {
  var Utils;

  Utils = class Utils {
    // expects item.value and item.length
    padString(item) {
      var ref, value;
      value = ((ref = item.value) != null ? ref.toString().trim() : void 0) || '';
      return value.toString().trim() + new Array(item.length).fill(' ').join('').substring(value.length);
    }

    // expects item.value and item.length
    padNumber(item) {
      var ref, value;
      value = ((ref = item.value) != null ? ref.toString().trim() : void 0) || '';
      return new Array(item.length).fill('0').join('').substring(value.length) + value;
    }

  };

  module.exports = Utils;

}).call(this);
